backend:
  name: github
  repo: vageesa/portfolio
  branch: master

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blogs"
    label: "Content"
    files:
      - label: "Professional Mode"
        name: "professional"
        file: "data/professional.json"
        fields:
          - {label: "About Text", name: "about_text", widget: "text", required: false}
          - label: "Experience"
            name: "experience"
            widget: "list"
            required: false
            fields:
              - {label: "Year/Period", name: "year", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
          - label: "Projects"
            name: "projects"
            widget: "list"
            required: false
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Link URL", name: "link", widget: "string", required: false}
              - {label: "Link Label", name: "link_label", widget: "string", default: "Case Study", required: false}
              - {label: "GitHub Repo URL", name: "github_link", widget: "string", required: false}
          - label: "Posts"
            name: "posts"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Date", name: "date", widget: "string"}
              - {label: "Excerpt", name: "excerpt", widget: "text"}
      - label: "Hobby Mode"
        name: "hobby"
        file: "data/hobby.json"
        fields:
          - {label: "About Text", name: "about_text", widget: "text", required: false}
          - label: "Milestones"
            name: "experience"
            widget: "list"
            required: false
            fields:
              - {label: "Year/Period", name: "year", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
          - label: "Creations"
            name: "projects"
            widget: "list"
            required: false
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Link URL", name: "link", widget: "string", required: false}
              - {label: "Link Label", name: "link_label", widget: "string", default: "Case Study", required: false}
              - {label: "GitHub Repo URL", name: "github_link", widget: "string", required: false}
          - label: "Posts"
            name: "posts"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Date", name: "date", widget: "string"}
              - {label: "Excerpt", name: "excerpt", widget: "text"}
